# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Se4TpIzm5wSCm738vpA2HpszzeRx7pbx
"""

class Conta:
  def __init__(self, numero, cpf, nomeTitular, saldo):
    self.numero = numero
    self.cpf = cpf
    self.nomeTitular = nomeTitular
    self.saldo = saldo

def main():
    c1 = Conta(1,1,"joão",1000) #Objeto sendo instanciado
    print(f'Nome do titular da conta: {c1.nomeTitular}')
    print(f'Número da conta: {c1.numero}')
    print(f'CPF do titular da conta: {c1.cpf}')
    print(f'Saldo da conta: {c1.saldo}')